### ISSUE TITLE
LocalFile#getPath raises InvalidPathException in Windows Platform

### ISSUE THREAD

**Issue by hiroyuki-sato** [embulk/embulk-output-sftp#27] opened 2017-03-27 08:36 UTC
See detail. 

Thank you @kazup0n.

https://github.com/embulk/embulk/issues/576#issuecomment-289387778

**Comment by sakama** [comment] 2017-03-27 14:03
I think the root cause is Embulk generates Temp file name using it's thread name that contains invalid characters `:`.
https://github.com/embulk/embulk/blob/master/embulk-core/src/main/java/org/embulk/spi/TempFileSpace.java#L30

I don't think any change is required at embulk-output-sftp.

**Comment by sakama** [comment] 2017-03-28 07:16
I close this issue. Please reopen if you have any concerns.

**Closed** 2017-03-28 07:16 UTC

**Comment by hiroyuki-sato** [comment] 2017-05-13 03:36
Embulk 0.8.19 fixed this issue.
http://www.embulk.org/docs/release/release-0.8.19.html
Fixed TempFileSpace to change temporary filename format for Windows safe.
